project:
  type: website
  output-dir: docs
  
website:
  title: "ESS 523c: Environmental Data Science"
  site-url: https://github.com/nedasfr/WR523c
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: labs/lab-01.qmd
        text: Lab 1
  